### ISSUE TITLE
bug: `unevaluatedProperties` is not working properly

### ISSUE THREAD

**Issue by AgniveshChaubey** [Relequestual/json-schema-dev#66]
I was reading [#550](https://github.com/json-schema-org/json-schema-spec/issues/556) to understand the behavior of `unevaluatedProperties` and when testing the below example 

![image](https://github.com/Relequestual/json-schema-dev/assets/113545196/9f2afd67-8e90-46cd-9ac9-fc633bae4135)

on jsonschema.dev, I found that the validation result does not match what is expected by the example.

for this schema
```json
{
    "title": "Vehicle",
    "type": "object",
    "oneOf": [
        {
            "title": "Car",
            "required": ["wheels", "headlights"],
            "properties": {
                "wheels": {},
                "headlights": {}
            }
        },
        {
            "title": "Boat",
            "required": ["pontoons"],
            "properties": {
                "pontoons": {}
            }   
        },  
        {
            "title": "Plane",
            "required": ["wings"],
            "properties": {
                "wings": {}
            }
        }
    ],
    "unevaluatedProperties": false
}
```

the instance `{ "headlights": {}, "pontoons": {} }` should fail, but it is unexpectedly passing. [(check this)](https://jsonschema.dev/s/adwaJ)

**Comment by Relequestual** [comment]
@AgniveshChaubey Thanks for reporting. You understand correctly, however right now it only supports draft-07, and not 2019-09 or 2020-12, so it will be treated as an unknown additional keyword, which is allowed and valid for draft-07.

There is a notice at the top which says the version supported is draft-07.

It would be nice if additional unknown keywords caused a warning, but that requires some work, which I don't currently have time for.

As such, I'm going to close this Issue.
